pipeline:

  my-build:
    privileged: true
    image: quay.io/ukhomeofficedigital/openjdk8:v1.1.0
    environment:
      - ARTIFACTORY_USER=${ARTIFACTORY_USERNAME}
      - ARTIFACTORY_PASS=${ARTIFACTORY_PASSWORD}
      - DOCKER_HOST=tcp://127.0.0.1:2375
      - PTTG_GH_TOKEN=${PTTG_GH_TOKEN}
    commands:
      - ./gradlew build artifactoryPublish
    when:
      event: push

services:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
